Try except in asyncio
cnumr/ecoindex_cli pull request #83
Opened 2021-11-05 07:00 UTC by mikefromlig

Hi,

Here is a modification for avoiding the app to crash when it cannot deal with one of the given urls.
A red line appears in the console, and a log file is created in /tmp/ecoindex-cli/output.
Please tell me what you think about it.

Best,
mike

2021-11-05 12:23 UTC, mikefromlig commented
Hi again,
Maybe I did something wrong here: this branch doesn't start from the current version of your code. Can you still handle this? Or should I redo something ?
mike

2021-11-07 14:01 UTC, vvatelot commented
Hello @mikefromlig thakks for this PR!
Are you sure your branch is based on the latest version of the master?
As I merged your last PR #80 in master, you have to pull master and rebase your development on it.

For this PR, can you tell me more about the issue you encounter? Is there an error message? Do you have example of failing urls?

2021-11-08 07:37 UTC, mikefromlig commented
Hello @vvatelot.
I rebased my branch on your master.
Here is the console log about the issue I encounter with `https://www.patoutrailsaintlary.com`

![Capture d’écran 2021-11-08 à 08 34 30](https://user-images.githubusercontent.com/20038979/140701748-5029517d-3ac3-4db6-81b8-855a22352416.png)

2021-11-08 09:35 UTC, vvatelot commented
Alright! I can reproduce this issue.
This is an issue in the parent package: https://github.com/cnumr/ecoindex_python

So, I propose to create an issue on the parent package to investigate this issue, and handle your proposal to temporarily fix the issue for the cli.

2021-11-08 09:42 UTC, vvatelot commented on ecoindex_cli/cli/app.py
> +            domain = urls_file.split("/")[-1]
Why did you add this ?

2021-11-08 09:42 UTC, vvatelot commented on ecoindex_cli/cli/app.py
> +            f.close()
Maybe it could be better to use python logger to do that? 
https://docs.python.org/3/howto/logging.html

What would be great:
- Use Python Logger
- Define multiple handlers: streamhandler and/or filehandler (could be extended later)
- Set logging configuration in separate file

So we should have a file `ecoindex_cli/logger.py` in which we define the logger and then in the `except Exception` you just call `logger.error(e.msg)`

2021-11-08 10:07 UTC, mikefromlig commented on ecoindex_cli/cli/app.py
> +            f.close()
Ok, I'll try to implement this.

2021-11-08 14:29 UTC, mikefromlig commented
I made a first version of logger.py, and I use it in app.py. 
Please tell me what you think.

2021-11-08 14:37 UTC, mikefromlig commented
I made a first version of logger.py, and I use it in app.py.
Please tell me what you think.

2021-11-08 22:22 UTC, vvatelot requested changes
Nice job for the logger!

2021-11-08 22:22 UTC, vvatelot commented on ecoindex_cli/cli/app.py
> +from os.path import dirname, exists
Can be removed

2021-11-08 22:22 UTC, vvatelot commented on ecoindex_cli/cli/app.py
> +    log = None
Not useful

2021-11-08 22:22 UTC, vvatelot commented on ecoindex_cli/cli/app.py
> +        log = logger(str(output_log))
```suggestion
        log = Logger(filename=output_log)
```

For a class, it is better to respect [CapsWord](https://www.python.org/dev/peps/pep-0008/#class-names) convention

2021-11-08 22:22 UTC, vvatelot commented on ecoindex_cli/cli/app.py
> +        err_found = False
```suggestion
        error_found = False
```

You can be explicit :)

2021-11-08 22:22 UTC, vvatelot commented on ecoindex_cli/cli/app.py
> +                        log.error("\n -- " + url + " --\n" + e.msg)
```suggestion
                        error_found = True
                        log.error(" -- " + url + " -- " + e.msg)
```

I prefer not adding line break. But it is only my vision, so can be debated ;)

2021-11-08 22:22 UTC, vvatelot commented on ecoindex_cli/cli/app.py
> +                f"\nErrors found: please look ar {output_log})",
```suggestion
                f"\nErrors found: please look at {output_log})",
```

2021-11-08 22:22 UTC, vvatelot commented on ecoindex_cli/logger.py
> +        logging.error(msg)
```suggestion
import logging

from ecoindex_cli.files import create_folder


class Logger:
    def __init__(self, filename: str) -> None:
        create_folder(path="/tmp/ecoindex-cli/logs")

        logging.basicConfig(
            filemode="w+", filename=filename, format="%(asctime)s %(message)s"
        )

    def error(self, msg: str) -> None:
        logging.error(msg)
```

2021-11-08 22:22 UTC, vvatelot commented on ecoindex_cli/logger.py
> +        logging.error(msg)
This way, we respect CapsWord convention and we also take care of the creation of the log folder when initializing logger instance

2021-11-08 22:23 UTC, vvatelot commented on ecoindex_cli/cli/app.py
> +        log = logger(str(output_log))
I also take advantage of named parameters which is a good practice

2021-11-10 08:36 UTC, mikefromlig commented on ecoindex_cli/logger.py
> +        logging.error(msg)
I made all the changes. Tell me.
mike

2021-11-10 08:38 UTC, mikefromlig commented
I made all the requested changes. Tell me.
mike

2021-11-17 10:03 UTC, mikefromlig commented
@vvatelot , do I have to do something more now ?

2021-11-17 10:56 UTC, vvatelot commented
Hello @mikefromlig I proposed you a PR: https://github.com/mikefromlig/ecoindex_cli/pull/1
It was easier to make a PR on your repo than propose changes on the current PR. So, what you should do is to validate the PR on your repo (or not...) and then tell me when your branch is up to date

2021-11-18 07:57 UTC, vvatelot approved these changes
Really thank you very much @mikefromlig ! Nice job!

2021-11-18 07:58 UTC, merged